version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=humanist
      - POSTGRES_USER=humanist
      - POSTGRES_PASSWORD=humanist
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  cache:
    image: redis

  web:
    build: .
    command: ./migrate_and_run.sh
    volumes:
      - .:/humanist
    ports:
      - "8080:8080"
    depends_on:
      - db
      - cache
    extra_hosts:
      # IMPORTANT: Replace ip with ip address of local network interface
      - "mailhost:192.168.178.68"
