version: "3"

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=humanist
      - POSTGRES_USER=humanist
      - POSTGRES_PASSWORD=humanist
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  cache:
    image: redis:6

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  web:
    build: .
    command: ./migrate_and_run.sh
    volumes:
      - .:/humanist
      # Location of all incoming mails in Maildir format
      - ${LOCAL_MAILDIR}:/maildir
    environment:
      # Should be the location of the volume above
      - HUMANIST_MAILDIR=/maildir
      # Public URL of the app
      - BASE_URL=${BASE_URL}
    ports:
      - "127.0.0.1:10000:8080"
    depends_on:
      - db
      - cache
      - search
    extra_hosts:
      - "mailhost:${MAILHOST_IP}"
