version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=humanist
      - POSTGRES_USER=humanist
      - POSTGRES_PASSWORD=humanist
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  cache:
    image: redis

  web:
    build: .
    command: ./migrate_and_run.sh
    volumes:
      - .:/humanist
      # Location of all incoming mails in Maildir format
      - /home/humanist/Maildir:/maildir
    environment:
      # Should be the location of the volume above
      - HUMANIST_MAILDIR=/maildir
      # Public URL of the app
      - BASE_URL=https://miskatonic.hki.uni-koeln.de
    ports:
      - "127.0.0.1:10000:8080"
    depends_on:
      - db
      - cache
    extra_hosts:
      # IMPORTANT: Replace ip with ip address of local network interface
      - "mailhost:134.95.80.110"
